#!/usr/bin/env bash
# This script displays a clock format from 0:01 to 12:59.

hour=0
while [ "$hour" -le 12 ]; do
    echo "Hour: $hour"
    minute=1
    while [ "$minute" -le 59 ]; do
        echo "$minute"
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done
