#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely.
# It prints "I am invincible!!!" when it receives a SIGTERM signal.

# trap: command to execute when a signal is received.
# "echo 'I am invincible!!!'": the command to run on SIGTERM.
# SIGTERM: the signal to trap (Software Termination Signal).
trap "echo 'I am invincible!!!'" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
