#!/usr/bin/env bash
# This script (daemon) continuously writes "I am alive!" to /tmp/my_process.

# Ensure the output file exists or can be created
touch /tmp/my_process

while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
